### ISSUE TITLE
Bug: PullSecret for catalog in imageset config does not work when headsOnly is true

### ISSUE THREAD

**Issue by jpower432** [RedHatGov/bundle#43]
When the pull secret is set in the imageset config, the value is not being passed when generating the diff with the heads only option. The 401 error occurs when action.Run trys to render the news refs.

https://github.com/estroz/operator-registry/blob/1787329c541ff5c4533d680df5f208805eee93ea/pkg/action/diff.go#L52

**Comment by jpower432** [comment]
The exact error is happening when `oc-bundle` is trying to pull down the index image to create the diff. Looks like the resolver is not exported for the registry. We would just need that exported so we can set the resolver options with the credentials we want.
https://github.com/estroz/operator-registry/blob/1787329c541ff5c4533d680df5f208805eee93ea/pkg/image/containerdregistry/registry.go#L50. @afflom @estroz FYSA.

**Comment by bit4man** [comment]
Pull secret seems to be ignored when pulling operators when it's only defined under "ocp" and not the operator definition.  Using "create full".

**Comment by jpower432** [comment]
@bit4man , you are correct. Each operator catalog take it's own pull secret value, but you also have the option to just put all of your pulll secrets in your .docker/config.json. If a pull secret value is not provided with the operator catalog in the config, it will just default to that file.

**Comment by bit4man** [comment]
> @bit4man , you are correct. Each operator catalog take it's own pull secret value, but you also have the option to just put all of your pulll secrets in your .docker/config.json. If a pull secret value is not provided with the operator catalog in the config, it will just default to that file.

@jpower432 Unfortunately, I get the same error when I put the pullSecret in the operator catalog entry.

**Comment by jpower432** [comment]
> > @bit4man , you are correct. Each operator catalog take it's own pull secret value, but you also have the option to just put all of your pulll secrets in your .docker/config.json. If a pull secret value is not provided with the operator catalog in the config, it will just default to that file.
> 
> @jpower432 Unfortunately, I get the same error when I put the pullSecret in the operator catalog entry.

@bit4man if you put your secret in your config.json, the error will go away. This ticket is actually capturing the issue you are seeing. When the catalog diff data is generated it uses a docker resolver that we are not passing credentials to because it is unexported.

**Comment by afflom** [comment]
Using `.docker/config.json` will have to suffice until the operator download code from operator-registry allows for configured credentials. My suggestion going forward is: keep the secrets out of the config file and allow for a separate auth-file reference when our operator-registry import allows.
