### ISSUE TITLE
Output of create diff does not update imageset file name

### ISSUE THREAD

**Issue by afflom** [RedHatGov/bundle#72]
When running create full, the output imageset name is bundle_000000.tar

When running create diff in the same workspace, the output imageset name is the same (bundle_000000.tar).

As a user, I would expect the name of the imageset to reflect the sequence number of the creation.

**Comment by jpower432** [comment]
@afflom The new prefix on imageset is `bundle_seq<sequence-number>_00000.tar`. Do you think that change is sufficient enough for this ticket to be closed?
