### ISSUE TITLE
File name too long "create full"

### ISSUE THREAD

**Issue by bit4man** [RedHatGov/bundle#74]
Running an initial "create full" that includes ubi8, I get a "FATAL error creating image resolver: <pull-secret>/config.json" where "<pull-secret>" is the content of the pull secret in the imageset-config file.  I have the following option in the additionalimages:

```
  additionalimages:
    - name: registry.redhat.io/ubi8/ubi:latest
```

Since the pull secret is long and shouldn't be included here, I'll just enclose the few lines before the error happens:

```
info: Planning completed in 2.59s
sha256:038b03c6db9a6484c7328c33eac4cb7b4d9f64a5a74c3849add4b000222f20c4 file://registry.redhat.io/ubi8/ubi
sha256:ba6956f6fabe47ecee824470fa3e3886e563c7b0e4a5240fe96effe559396234 file://registry.redhat.io/ubi8/ubi
sha256:4ce314c597d03077198d51cdf0421d567234bb559e912b89fbbbfa87ed67dc1f file://registry.redhat.io/ubi8/ubi
sha256:08117490cf2a61a85d560f87a5dac3516c043dc092319880f3874b6b6982e71b file://registry.redhat.io/ubi8/ubi
sha256:7254254afafd44c850940445c0480e449fea73a169aa067389252fef35bd7a3f file://registry.redhat.io/ubi8/ubi:latest
info: Mirroring completed in 0s (0B/s)
FATAL error creating image resolver: {"auths":{"cloud.openshift.com"......................
```

**Comment by bit4man** [comment]
Removing the pull-secrets from the imageset-config file seems to have bypassed this issue.

**Comment by afflom** [comment]
Auth handing will be addressed during alpha3 (ux improvements). Users shouldn't encouinter the behavior seen in this issue if they add secrets to `~/.docker/conf.json`.  I've added #78 to alpha3 to address this
