### ISSUE TITLE
oc-bundle publish duplicates an uncompressed archive?

### ISSUE THREAD

**Issue by bit4man** [RedHatGov/bundle#77]
The size of the generated tar-ball is immense -- 100+GB. Duplicating it to disk before running the publish seems a big waste. Suggest processing the file without extracting to disk first, or extract small portions, process, and delete the temporary files, and continue with the next set of files.

**Comment by afflom** [comment]
This will be addressed in the first tagged release.

**Comment by afflom** [comment]
https://github.com/RedHatGov/bundle/issues/61
