### ISSUE TITLE
Handle multiple credentials

### ISSUE THREAD

**Issue by afflom** [RedHatGov/bundle#9]
- Load registry pull secrets from imageset-config. 
- Handle multiple credential strings (multiple registries) 

background: Allow users to add separate registry credentials instead of editing serialized json in the red hat pull secret.

**Comment by jpower432** [comment]
@afflom At this point here we are loading creds directly from the imageset-config.yaml. Wondering if we should have a fallback option of getting the secret from the standard docker config.json location if the pullSecret isn't provided. WYDT?
